WIP: Improvements for build and delivery
mixbytes/haya pull request #39
Opened 2019-10-03 17:45 UTC by alevkin

- Added build scripts for CentOS, Ubuntu
- Added push assets to GitHub Releases
- WIP for MacOS

2019-10-08 12:34 UTC, algys commented
Please add minimal readme (how to build pkg, docker etc.)

2019-10-08 12:35 UTC, algys requested changes
need minimal readme/how-to/examples

2019-10-10 09:29 UTC, alevkin commented
> Please add minimal readme (how to build pkg, docker etc.)

Done

2019-10-10 09:41 UTC, algys approved these changes

2019-10-10 09:43 UTC, algys commented
build failed, so probably have some issues in CMakeLists.txt

2019-10-10 09:43 UTC, algys requested changes
fix build

2019-10-10 11:32 UTC, algys approved these changes

2019-10-10 11:38 UTC, merged

2019-10-18 09:57 UTC, Eenae commented on cicd/run
> +      echo "Usage: $ProgName build [options] {projact_name}"
projact